name: aiying_video
description: 爱影视频 Flutter 应用

# 应用版本号
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # 状态管理
  flutter_riverpod: ^2.4.9
  
  # 网络请求
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  
  # 本地存储
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # UI组件
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  
  # 视频播放
  video_player: ^2.8.1
  chewie: ^1.7.4
  
  # WebView
  webview_flutter: ^4.4.2
  
  # 国际化
  intl: ^0.18.1
  
  # 工具
  url_launcher: ^6.2.2
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.1
  path_provider: ^2.1.1
  
  # 权限处理
  permission_handler: ^11.0.1
  
  # 支付
  in_app_purchase: ^3.1.11
  
  # 路由
  go_router: ^13.0.1
  
  # 图片选择和处理
  image_picker: ^1.0.4
  image_cropper: ^5.0.1
  
  # 二维码扫描
  mobile_scanner: ^3.5.2
  
  # 通知
  flutter_local_notifications: ^16.1.0
  
  # 分享
  share_plus: ^7.2.1
  
  # 日志
  logger: ^2.0.2+1
  
  # 下拉刷新
  pull_to_refresh: ^2.0.0
  
  # 加密
  crypto: ^3.0.3
  
  # 图表（可选，用于数据展示）
  fl_chart: ^0.65.0
  
  # 广告（可选）
  google_mobile_ads: ^4.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6

# Flutter应用图标配置
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"

# 启动屏配置
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/splash_logo.png"
  android_12:
    image: "assets/images/splash_logo_android12.png"
    icon_background_color: "#FFFFFF"
  ios: true

# Flutter配置
flutter:
  uses-material-design: true
  
  # 资源文件
  assets:
    - assets/images/
    - assets/icons/
  
  # 字体配置
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
  
  # 生成本地化代码
  generate: true 